# Generated by Django 5.2 on 2025-04-28 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DauSach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_sach", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TacGia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_tac_gia", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TheLoai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_the_loai", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Sach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nxb", models.CharField(max_length=200)),
                ("nam_xb", models.IntegerField()),
                ("slton", models.IntegerField()),
                (
                    "dau_sach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sach",
                        to="api.dausach",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dausach",
            name="tac_gia",
            field=models.ManyToManyField(related_name="dau_sach", to="api.tacgia"),
        ),
        migrations.AddField(
            model_name="dausach",
            name="the_loai",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dau_sach",
                to="api.theloai",
            ),
        ),
    ]
